In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os 
import sys
import time
import tensorflow as tf
from tensorflow import keras

F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 

In [2]:
#strings

t = tf.constant("cafe")

print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit="UTF8_CHAR"))
#将t转化为UTF8编码
print(tf.strings.unicode_decode(t,"UTF8"))

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [3]:
#ragged tensor
r = tf.ragged.constant([[11,12],[12,11,14,23],[],[23]])
r2 = tf.ragged.constant([[11,12],[12,11,14,23],[],[23]])

print(r)
print(r[0])
print(r[0:3])
print("#"*100)

#拼接操作
print(tf.concat([r,r2],axis=0))
print(tf.concat([r,r2],axis=1))
print("#"*100)

print(r.to_tensor())

<tf.RaggedTensor [[11, 12], [12, 11, 14, 23], [], [23]]>
tf.Tensor([11 12], shape=(2,), dtype=int32)
<tf.RaggedTensor [[11, 12], [12, 11, 14, 23], []]>
####################################################################################################
<tf.RaggedTensor [[11, 12], [12, 11, 14, 23], [], [23], [11, 12], [12, 11, 14, 23], [], [23]]>
<tf.RaggedTensor [[11, 12, 11, 12], [12, 11, 14, 23, 12, 11, 14, 23], [], [23, 23]]>
####################################################################################################


W0913 20:14:11.376270  3372 deprecation.py:323] From F:\Anaconda3\lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py:1553: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


tf.Tensor(
[[11 12  0  0]
 [12 11 14 23]
 [ 0  0  0  0]
 [23  0  0  0]], shape=(4, 4), dtype=int32)
