# 创建Tensor

In [1]:
import tensorflow as tf

F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
F:\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is 

In [4]:
#正态分布，默认为N~~~（0,1）分布
tf.random.normal([2,2], mean=1, stddev=1)

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[-0.30167365,  0.3251887 ],
       [ 1.0831875 ,  1.9850175 ]], dtype=float32)>

In [5]:
#截断的正态分布
tf.random.truncated_normal([2,2], mean=0, stddev=1)

<tf.Tensor: id=32, shape=(2, 2), dtype=float32, numpy=
array([[ 1.0576699 ,  0.8487729 ],
       [ 0.22840786, -0.29953164]], dtype=float32)>

In [8]:
#均匀分布
tf.random.uniform([2,2],minval=0,maxval=100,dtype=tf.int32)

<tf.Tensor: id=45, shape=(2, 2), dtype=int32, numpy=
array([[71, 35],
       [13, 90]])>

In [10]:
#随机打散
a = tf.range(10)
b = tf.random.shuffle(a)
print(b)

tf.Tensor([3 0 7 5 9 8 2 4 1 6], shape=(10,), dtype=int32)


# 索引和切片

In [14]:
a = tf.ones([1,5,5,3])
print(a[0][0])
print('*'*100)
print(a[0][0][0])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)
****************************************************************************************************
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


### :以及::的切片方式与np类似

In [18]:
a = tf.random.normal([2,4,28,28,3])
print(a[0,...].shape)
print('#'*100)
print(a[...,0].shape)

(4, 28, 28, 3)
####################################################################################################
(2, 4, 28, 28)


# Selective Indexing

In [ ]:
tf.gather()
tf.gather_nd()

# boardcasting

# 分割与合并

In [3]:
#合并---并不增加维度
a = tf.ones([4,5,6])
b = tf.ones([3,5,6])
c = tf.concat([a,b],axis=0)
c.shape

TensorShape([7, 5, 6])

In [6]:
#堆叠---增加维度
a = tf.ones([4,5,6])
b = tf.ones([4,5,6])
c = tf.stack([a,b],axis=0)
d = tf.stack([a,b],axis=3)
print(c.shape)
print(d.shape)

#unstack与stack互为逆操作

(2, 4, 5, 6)
(4, 5, 6, 2)


In [8]:
e = tf.ones([4,5,6,8])
f = tf.split(e,axis=3,num_or_size_splits=4)
len(f)
f[0].shape

TensorShape([4, 5, 6, 2])

# 张量排序

In [11]:
a = tf.random.shuffle(tf.range(0,10))
print(a)
#返回值
print(tf.sort(a,direction='DESCENDING'))
#返回位置
print(tf.argsort(a,direction='DESCENDING'))

tf.Tensor([8 0 2 5 7 6 1 3 4 9], shape=(10,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)
tf.Tensor([9 0 4 5 3 8 7 2 6 1], shape=(10,), dtype=int32)


In [16]:
#top_k为返回最大的前K个值
a = tf.random.uniform([3,3],maxval=10,dtype=tf.int32)
print(a)
print('*'*100)
res = tf.math.top_k(a,2)
print(res.indices)
print('*'*100)
print(res.values)

tf.Tensor(
[[6 0 0]
 [5 5 7]
 [7 0 4]], shape=(3, 3), dtype=int32)
****************************************************************************************************
tf.Tensor(
[[0 1]
 [2 0]
 [0 2]], shape=(3, 2), dtype=int32)
****************************************************************************************************
tf.Tensor(
[[6 0]
 [7 5]
 [7 4]], shape=(3, 2), dtype=int32)


# 填充与复制

In [5]:
a = tf.reshape(tf.range(9),[3,3])
print(a)
print('*'*100)
#第二个参数中，【0,1】表示填充过程中：上0下1，【1,0】表示左1右0（行）
b = tf.pad(a,[[0,1],[1,0]])
print(b)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
****************************************************************************************************
tf.Tensor(
[[0 0 1 2]
 [0 3 4 5]
 [0 6 7 8]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [6]:
c = tf.reshape(tf.range(9),[3,3])
#tile复制
#【1,2】表示第一个维度复制1次，第二个维度复制两次
d = tf.tile(c,[1,2])
print(d)

tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(3, 6), dtype=int32)
