# axis（轴）


### 若是二维，0轴代表x轴，1轴代表y轴
### 若是三维，0轴代表通道，1轴代表x轴，2轴代表y轴

In [1]:
import numpy as np


# 转置的几种方法

In [6]:

a = np.arange(24).reshape((4,6))
# a.transpose()
# a.T
# a.swapaxes(1,0)

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

# numpy索引和切片

In [23]:
b = np.arange(50).reshape((10,5))
print(b)
print("#"*100)

#取行
print(b[0])
print("#"*100)


#取连续多行
print(b[0:3])
print("#"*100)

#取不连续多行
print(b[[2,4,8]])
print("#"*100)

#取列
print(b[:,0])
print("#"*100)


#取连续多列
print(b[:,2:5])
print("#"*100)

#取不连续多列
print(b[:,[0,2,3]])
print("#"*100)

#取3到5行，2到4列的值
print(b[2:5,1:4])
print("#"*100)

#取多个不相邻的点（0,0）（2,1）
print(b[[0,2],[0,1]])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
####################################################################################################
[0 1 2 3 4]
####################################################################################################
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
####################################################################################################
[[10 11 12 13 14]
 [20 21 22 23 24]
 [40 41 42 43 44]]
####################################################################################################
[ 0  5 10 15 20 25 30 35 40 45]
####################################################################################################
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]
 [32 33 34]
 [37 38 39]
 [42 43 44]
 [47 48 49]]
#######################################

# numpy对数值的修改

In [26]:
#将小于10的值改为0
b[b<10] = 0
print(b)
print("#"*100)


np.where(b<25,100,300)


#b.clip(10,18)将小于等于10的替换为10，大于等于18的替换为18



[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
####################################################################################################


array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300],
       [300, 300, 300, 300, 300]])