In [2]:
import numpy as np

In [8]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(50,74).reshape((4,6))


In [9]:
#竖直拼接
np.vstack((t1,t2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73]])

In [10]:
#水平拼接
np.hstack((t1,t2))

array([[ 0,  1,  2,  3,  4,  5, 50, 51, 52, 53, 54, 55],
       [ 6,  7,  8,  9, 10, 11, 56, 57, 58, 59, 60, 61],
       [12, 13, 14, 15, 16, 17, 62, 63, 64, 65, 66, 67],
       [18, 19, 20, 21, 22, 23, 68, 69, 70, 71, 72, 73]])

In [17]:
#将第一行与第三行进行交换
t = np.arange(12,24).reshape((3,4))


t[[0,2],:] = t[[2,0],:]

print(t)

[[20 21 22 23]
 [16 17 18 19]
 [12 13 14 15]]


In [16]:
#将第一列与第三列进行交换
tt = np.arange(12,24).reshape((3,4))
tt[:,[0,2]] = tt[:,[2,0]]
print(tt)

[[14 13 12 15]
 [18 17 16 19]
 [22 21 20 23]]


In [23]:
tt = np.eye(5)

#获取最大值，最小值的位置
np.argmax(tt,axis=0)



array([0, 1, 2, 3, 4], dtype=int64)

In [24]:
ttt = np.eye(6)
np.argmin(ttt,axis=1)

array([1, 0, 0, 0, 0, 0], dtype=int64)