In [1]:
import numpy as np


In [11]:
a = np.arange(12)

b = a.reshape(3,4)

print(b)






[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
#拉伸为一维数组
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#广播，加减乘除都适用
c = a+2
print(c)


[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [28]:
q = np.arange(12)

w = a.reshape(3,4)


x = np.arange(110,122).reshape(3,4)

print(x+w)

t1 = np.arange(0,4)
print(x-t1)

[[110 112 114 116]
 [118 120 122 124]
 [126 128 130 132]]
[[110 110 110 110]
 [114 114 114 114]
 [118 118 118 118]]
