In [2]:
import tensorflow as tf

In [3]:
tf.zeros([3,4], dtype='int32')

<tf.Tensor 'zeros:0' shape=(3, 4) dtype=int32>

In [4]:
tensor = [[1,2,3],[4,5,6]]
tf.zeros_like(tensor)
tf.ones_like(tensor)

<tf.Tensor 'ones_like:0' shape=(2, 3) dtype=int32>

In [5]:
tf.linspace(10.0,12.0,3,name="linspace") = =>[10.0,11.0,12.0]

SyntaxError: invalid syntax (<ipython-input-5-78f470ad5f80>, line 1)

In [ ]:
tf.range(start,end,delta)


In [ ]:
norm = tf.random_normal([2,3],mean=-1,stddev=4)  #高斯分布的矩阵，均值-1，方差4

sess = tf.Session()
print(sess.run(norm))

In [ ]:
#洗牌操作


c = tf.constant([[1,2],[3,4],[5,6]])


shuff = tf.random_shuffle(c)

sess = tf.Session()
print(sess.run(shuff))

In [ ]:
state = tf.Variable(0)
new_value = tf.add(state,tf.constant(1))
update = tf.assign(state,new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

In [ ]:
#将numpy转换为tf
import numpy as np

c = np.zeros((3,4))
ta = tf.convert_to_tensor(c)

with tf.Session() as sess:
    print(sess.run(ta))

In [12]:
sess = tf.InteractiveSession()


arr = np.random.randint(0,10,(4,3))

print(arr)

#tf.rank(arr).eval():矩阵的维数
#tf.shape(arr).eval():矩阵的形状

#tf.argmax(arr,1).eval():返回矩阵最大值的索引，0代表按列顺序，1代表按行顺序


[[5 4 5]
 [4 3 3]
 [6 8 1]
 [8 8 7]]


array([0, 0, 1, 0], dtype=int64)