In [1]:
import tensorflow as tf


In [2]:
v1 = tf.Variable(tf.random_normal([1,2],name="v1"))
v2 = tf.Variable(tf.random_normal([2,3],name="v2"))
init_op = tf.global_variables_initializer()

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(v1))
    print("#"*100)
    print(sess.run(v2))
    print("#"*100)
    save_path = saver.save(sess,"save/model.ckpt")
    print("model save in :",save_path)

Instructions for updating:
Colocations handled automatically by placer.
[[-1.0475043   0.12091868]]
####################################################################################################
[[ 1.2037245 -0.7830084  0.5061059]
 [-1.0907354  0.4663608 -0.7006576]]
####################################################################################################
model save in : save/model.ckpt


In [1]:
import tensorflow as tf
v1 = tf.Variable(tf.random_normal([1,2],name="v1"))
v2 = tf.Variable(tf.random_normal([2,3],name="v2"))


saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess,"save/model.ckpt")
    print(sess.run(v1))
    print("#"*100)
    print(sess.run(v2))
    print("#"*100)
    print("model restore")

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from save/model.ckpt
[[-1.0475043   0.12091868]]
####################################################################################################
[[ 1.2037245 -0.7830084  0.5061059]
 [-1.0907354  0.4663608 -0.7006576]]
####################################################################################################
model restore
